### PR TITLE
Fix for a new bug and modified .env.example file

### PR DESCRIPTION
**Pull request by s-vamshi**
As env variable names in react must with REACT_APP_ changed the variable names.
Found a bug - incorrect import path for App.js in index.js. Fixed this bug.

### CODE REVIEW

**Comment by adeshpande7206** [comment]
Hey, the env files are not for react.

**Comment by adeshpande7206** [comment]
Just revert the changes corresponding to env files and I'll merge these

**Comment by s-vamshi** [comment]
Hey i have reverted changes made in env file.
Can you review my PR?

**Comment by adeshpande7206** [comment]
Just fetch upstream and update your PR. It has conflicts.

**Pull request closed without merging**
